### ISSUE TITLE
Alternative for Kong Community Edition?

### ISSUE THREAD

**Issue by mirkorose** [yesinteractive/kong-jwt2header#1]
This plugin was exactly what I was looking for.
Unfortunately it has a dependency to  the OpenId Connect plugin (https://docs.konghq.com/hub/kong-inc/openid-connect/) which is only available for the Kong Enterprise version, which I do not use.

As I do not expect you to change that dependency, maybe you know an easy way to get out the claims of a JWT without using the Enterprise version of Kong?

Background: I need to get a user id out of the JWT and map it to another id used in a third party system for the upstream request to that system.

**Comment by tovbinm** [comment]
How about this one instead? - https://luarocks.org/modules/olivine-labs/jwt

Update: I tried going down the rabbit hole of using the `jwt` module by Olivine Labs, but it involves installing numerous additional libraries, e.g. luacrypto, lua-cjson-ol, basexx, which require a lot of native libraries to be present. 

I wonder if there is a better alternative? In gneral JWT are not difficult to parse just using standard tools of json, base64 etc.

**Comment by tovbinm** [comment]
I found these plugins instead - https://github.com/wego/kong-jwt-claim-headers and https://github.com/wshirey/kong-plugin-jwt-claims-headers

**Comment by mirkorose** [comment]
Thanks for the input! Will give those plugins a try when coming back to Kong and API Gateway in the beginning of next year.

**Comment by cybrrnick** [comment]
Hey folks, this has been updated to support community edition as of today. Plugin now uses the community jwt library and works with both kong community and enterprise.

**Comment by tovbinm** [comment]
Thank you!! @nikirago

**Comment by mirkorose** [comment]
Thanks @nikirago !
