### ISSUE TITLE
Error in definition of 'kong-jwt2header'

### ISSUE THREAD

**Issue by dwking2000** [yesinteractive/kong-jwt2header#2]
I am using Kong EE latest. I have added the kong-jwt2header lua package to my docker image by using this method: 
https://github.com/Kong/docker-kong/tree/master/customize

When I run my customized image without enabling the plugin, I can see that it is installed in correct location. However when I enable it on docker run with  KONG_PLUGINS=bundled,kong-jwt2header  I get the following error:

`nginx: [warn] [lua] plugins.lua:227: load_plugin(): plugin 'route-by-header' has been deprecated
2020/10/19 04:01:18 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:536: error loading plugin schemas: on plugin 'kong-jwt2header': error initializing schema for plugin: error in definition of 'kong-jwt2header': run_on: cannot create a new field
stack traceback:
        [C]: in function 'assert'
        /usr/local/share/lua/5.1/kong/init.lua:536: in function 'init'
        init_by_lua:3: in main chunk
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:536: error loading plugin schemas: on plugin 'kong-jwt2header': error initializing schema for plugin: error in definition of 'kong-jwt2header': run_on: cannot create a new field
stack traceback:
        [C]: in function 'assert'
        /usr/local/share/lua/5.1/kong/init.lua:536: in function 'init'
        init_by_lua:3: in main chunk`

**Comment by cybrrnick** [comment]
Hello, this has been fixed as of today for Kong 2.x versions.
